version: '3.9'

volumes:
  db:

services:
  mysql:
    image: mariadb:10.9.4
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=db
      - MYSQL_PASSWOD=db
      - MYSQL_DATABASE=db
    volumes:
      - db:/var/lib/mysql