version: '3.9'

volumes:
  db:

services:
  spring:
    build: .
    image: spring-backend
    ports:
      - 8080:8080
  mariadb:
    image: mariadb:10.9.4
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=test123
      - MYSQL_USER=db
      - MYSQL_PASSWOD=db
      - MYSQL_DATABASE=db
    volumes:
      - db:/var/lib/mysql